(function() {var implementors = {};
implementors['syntex_syntax'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/util/interner/struct.RcStr.html' title='syntex_syntax::util::interner::RcStr'>RcStr</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/ast/struct.Ident.html' title='syntex_syntax::ast::Ident'>Ident</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/ast/struct.Name.html' title='syntex_syntax::ast::Name'>Name</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/ast/struct.DefId.html' title='syntex_syntax::ast::DefId'>DefId</a>","impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/owned_slice/struct.OwnedSlice.html' title='syntex_syntax::owned_slice::OwnedSlice'>OwnedSlice</a>&lt;T&gt;","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/parse/parser/struct.Restrictions.html' title='syntex_syntax::parse::parser::Restrictions'>Restrictions</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='syntex_syntax/parse/token/struct.InternedString.html' title='syntex_syntax::parse::token::InternedString'>InternedString</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
